export enum ErrorEnum {
    codeIncorrect = 'Code not valid!',
    passPhoneIncorrect = 'Username or password is incorrect!',
    passIncorrect = 'Password is incorrect!',
    nameUsed = 'This name is already in use!',
    EmployeeComp = 'The employee already has a computer!',
    phoneUsed = 'This phone is already in use!',
    loginUsed = 'This login is already in use!',
    UserNotFound = 'User not found!',
    NotFound = 'Not found!',
    fileNotFound = 'File not found!',
    imgNotFound = 'Image not found!',
    token = 'Token is required!',
    permission_access = 'You have not permission to access!',
    language = 'language is required!',
    invalidData = 'You have send invalid data',
    errorServer = 'Internal server error!',
    equalPasswords = 'Password and repeat password not equal!',
    Unauthorized = 'Unauthorized',
    roleUsed = 'This role is used by Staff',
}